name: gamma_ensemble_resnet_18
program: ../../../scripts/run.py
method: grid

metric:
  name: loss/val
  goal: minimize
parameters:
  data_dir:
    value: /home/ekellbuchanan/pytorch_datasets/cifar10_ood/data
  gamma:
    values: [1]
  max_epochs:
    value: 100
  logger:
    value: 'wandb'
  num_workers:
    value: 8
  module:
    value: 'casregress_ensemble_jgap_onehot'
  accelerator:
    value: 'ddp'
  gpus:
    value: 8
  learning_rate:
    value: 1e-2
  weight_decay:
    value: 1e-2
  batch_size:
    value: 256
  classifier:
    value: "densenet161"
  scheduler:
    value: "cosine"
# auto_lr_find:
#    value: 0
# gpu_id:
#   value: "0"

command:
  - ${env}
  - python
  - ${program}
  - "--config-name"
  - "run_default_gpu"
  - ${args_no_hyphens}
