name: tinyimagenet_base_resnet101
program: ../../../scripts/run_tinyimagenet.py
method: grid

metric:
  name: loss/val
  goal: minimize
parameters:
  data_dir:
    value: /home/ekellbuchanan/pytorch_datasets/tiny-imagenet-200
  gamma:
    value: 1
  max_epochs:
    value: 150
  logger:
    value: 'wandb'
  num_workers:
    value: 8
  module:
    value: 'base'
  accelerator:
    value: 'ddp'
  gpus:
    value: 8
  learning_rate:
    values: [1e-1, 1e-2]
  weight_decay:
    value: 1e-4
  classifier:
    value: 'resnet101'
  batch_size:
    value: 256

command:
  - ${env}
  - python
  - ${program}
  - "--config-name"
  - "run_default_gpu_tinyimagenet"
  - ${args_no_hyphens}