# Program arguments: 
data_dir: /home/ubuntu/cifar10_ood/data/ 
ood_dataset: cifar10_1  
version: v4 
level: null  
corruption: null
deterministic: 0
softmax_targets_train: /path/to/softmax
softmax_targets_eval_ind: /path/to/softmax
softmax_targets_eval_ood: /path/to/softmax
seed: null  
random_eval: 0
test_phase: 0   
dev: 0  
logger: "tensorboard"  
checkpoint: null  
softmax: 1  
nb_models: 4  
module: base  

# Trainer arguments 
classifier: densenet121  
gamma: 1 ## weight of dkl argument. 
embedding_dim: 25 ## attention embedding
start_attention: 10 ## epoch on which to start attentio
pretrained: 0 ## if we use pretrained models or not. 
pretrained-path: null ## path to pretrained model
precision: 32  
batch_size: 256  
max_epochs: 200  
num_workers: 8  
gpu_id: "0"  
learning_rate: 1e-2  
weight_decay: 1e-2  
test_set: "CIFAR10"  
lamb: 0.5  
scheduler: cosine  

