# Program arguments:
project: imagenet
data_dir: /home/ekellbuch/pytorch_datasets/imagenet
ood_dataset:
num_classes: 1000
test_set: "imagenet"

version: v4
level: null  
corruption: null
deterministic: 0
seed: null  
test_phase: 0   
dev: 1  
logger: "tensorboard"
checkpoint: null  
softmax: 1  
nb_models: 4
module: base

# Trainer arguments 
classifier: resnet18  
pretrained: 0  
pretrained-path: null  
precision: 32  
batch_size: 256
max_epochs: 100
gpu_id: null
learning_rate: 1e-1
weight_decay: 1e-4
scheduler: lambdalr

callbacks: 0 ## whether to use callbacks to debug.
random_eval: 0

lamb: 0.5
gamma: 1

num_workers: 4
#gpu strategy
