# Program arguments: 
data_dir: /Users/taigaabe/Code/ 
ood_dataset: cifar10_1  
version: v4 
level: null  
corruption: null
deterministic: 0
seed: null  
test_phase: 0   
dev: 1  
logger: "tensorboard"  
checkpoint: null  
softmax: 1  
nb_models: 4  
module: base  
# Trainer arguments 
classifier: resnet18  
pretrained: 0  
pretrained-path: null  
precision: 32  
batch_size: 256  
max_epochs: 100  
num_workers: 8  
gpu_id: "0"  
learning_rate: 1e-2  
weight_decay: 1e-2  
test_set: "CIFAR10"  
lamb: 0.5  
scheduler: cosine  

