# Program arguments:
# resnet18 this should be train/acc=100%, val/acc=74%
# wide_resnet this should be train/acc=100%, val/acc~60%
data_dir: /home/ubuntu/cifar10_ood/data/
ood_dataset: CIFAR100  
callbacks: 0 ## whether to use callbacks to debug. 
random_eval: 0
version: v4 
level: null  
corruption: null
deterministic: 0
seed: null  
test_phase: 0   
dev: 0
logger: "tensorboard"  
checkpoint: null  
softmax: 1  
nb_models: 4  
module: ensemble
num_classes: 100

# Trainer arguments 
classifier: resnet18_cifar100  
gamma: 1 ## weight of dkl argument. 
pretrained: 0 ## if we use pretrained models or not.
pretrained-path: null ## path to pretrained model
precision: 32  
batch_size: 128

max_epochs: 160
learning_rate: 1e-1
weight_decay: 5e-4  
test_set: "CIFAR100"  
scheduler: step

# gpu strategy
num_workers: 8
gpus: 1
accelerator: null 

# attention arguments for attention ensemble
lamb: 0.5  #attention ensemble
embedding_dim: 25 ## attention embedding
start_attention: 10 ## epoch on which to start attentio
