# Program arguments:
# data arguments
data_dir: /home/ekellbuch/pytorch_datasets/tiny-imagenet-200"
ood_dataset:
num_classes: 200
test_set: "tiny-imagenet"

callbacks: 0 ## whether to use callbacks to debug. 
version: v4 
level: null  
corruption: null
deterministic: 0
seed: null  
test_phase: 0   
dev: 0
logger: "tensorboard"  
checkpoint: null
softmax: 1  
nb_models: 4  
module: ensemble_dkl

# model arguments
resnet_stride: 1
classifier: resnet18

# Trainer arguments 
classifier: resnet34  
resnet_stride: 2
random_eval: 0
gamma: 1 ## weight of dkl argument. 
pretrained: 0 ## if we use pretrained models or not.
pretrained-path: null ## path to pretrained model
precision: 32
batch_size: 100
max_epochs: 200  
learning_rate: 1e-3
weight_decay: 1e-2  
scheduler: cosine

auto_lr_find: 0

num_workers: 32 
# gpu strategy
gpus: 4
accelerator: "ddp"
gpu_id: "0"

label_smoothing: 0

# attention arguments for attention ensemble
lamb: 0.5  #attention ensemble
embedding_dim: 25 ## attention embedding
start_attention: 10 ## epoch on which to start attentio
