# Program arguments: 
data_dir: /Users/taigaabe/Code/cifar10_ood/data/ 
ood_dataset: cifar10_1  
callbacks: 0 ## whether to use callbacks to debug. 
version: v4 
level: null  
corruption: null
deterministic: 0
seed: null  
test_phase: 0   
dev: 0
logger: "tensorboard"  
checkpoint: null  
softmax: 1  
nb_models: 4  
module: ensemble_dkl

# Trainer arguments 
classifier: resnet18  
random_eval: 0
gamma: 1 ## weight of dkl argument. 
pretrained: 0 ## if we use pretrained models or not.
pretrained-path: null ## path to pretrained model
precision: 32  
batch_size: 256  
max_epochs: 100  
learning_rate: 1e-2
weight_decay: 1e-2  
test_set: "CIFAR10"  
scheduler: cosine

# gpu stratefy
strategy: "dp"
num_workers: 8
gpu_id: "0"

# attention arguments for attention ensemble
lamb: 0.5  #attention ensemble
embedding_dim: 25 ## attention embedding
start_attention: 10 ## epoch on which to start attentio
