name: tinyimagenet_ensemble_jgap_resnet34
program: ../../../scripts/run_tinyimagenet.py
method: grid

metric:
  name: loss/val
  goal: minimize
parameters:
  data_dir:
    value: /home/ekellbuchanan/pytorch_datasets/tiny-imagenet-200
  gamma:
    values: [0.0, 0.5, 0.7, 1.0, 1.5, 2.0]
  max_epochs:
    value: 200
  logger:
    value: 'wandb'
  num_workers:
    value: 8
  module:
    value: 'ensemble_jgap'
  accelerator:
    value: 'ddp'
  gpus:
    value: 8
  learning_rate:
    value: 1e-1
  weight_decay:
    value: 1e-4
  classifier:
    value: 'resnet34'
  batch_size:
    value: 256
  nb_models:
    value: 3

command:
  - ${env}
  - python
  - ${program}
  - "--config-name"
  - "run_default_gpu_tinyimagenet"
  - ${args_no_hyphens}